#!/bin/bash

PATH=$PATH:$HOME/go/bin

STAGED_GO_FILES=$(git diff --cached --name-only --diff-filter=ACM| grep "\.go$")

if [[ "$STAGED_GO_FILES" = "" ]]; then
  exit 0
fi

PASS=true
exec 5>&1
for FILE in $STAGED_GO_FILES
do
  goimports -w $FILE

  gofmt -l -w $FILE

  golint "-set_exit_status" $FILE
  if [[ $? == 1 ]]; then
    PASS=false
  fi

  go vet $FILE
  if [[ $? != 0 ]]; then
    PASS=false
  fi
done

if ! golangci-lint run --timeout 5m -E revive -E rowserrcheck -E sqlclosecheck -E gosec 2>&1; then
  PASS=false
fi

if ! $PASS; then
  printf "COMMIT FAILED\n"
  exit 1
else
  printf "COMMIT SUCCEEDED\n"
fi

exit 0